[2025-04-06T20:00:03.770+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: googlemaps_api.run_API_GM scheduled__2025-04-06T19:00:00+00:00 [queued]>
[2025-04-06T20:00:03.790+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: googlemaps_api.run_API_GM scheduled__2025-04-06T19:00:00+00:00 [queued]>
[2025-04-06T20:00:03.791+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-04-06T20:00:03.816+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): run_API_GM> on 2025-04-06 19:00:00+00:00
[2025-04-06T20:00:03.825+0000] {standard_task_runner.py:57} INFO - Started process 54 to run task
[2025-04-06T20:00:03.831+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'googlemaps_api', 'run_API_GM', 'scheduled__2025-04-06T19:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/dag_gm.py', '--cfg-path', '/tmp/tmpspe6tfu6']
[2025-04-06T20:00:03.837+0000] {standard_task_runner.py:85} INFO - Job 4: Subtask run_API_GM
[2025-04-06T20:00:03.921+0000] {task_command.py:416} INFO - Running <TaskInstance: googlemaps_api.run_API_GM scheduled__2025-04-06T19:00:00+00:00 [running]> on host 4f8dac0cd162
[2025-04-06T20:00:04.165+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='googlemaps_api' AIRFLOW_CTX_TASK_ID='run_API_GM' AIRFLOW_CTX_EXECUTION_DATE='2025-04-06T19:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-06T19:00:00+00:00'
[2025-04-06T20:00:05.219+0000] {credentials.py:566} INFO - Found credentials in environment variables.
[2025-04-06T20:00:16.182+0000] {logging_mixin.py:151} INFO - [S3]Restaurant Restaurant Fil Manila uploaded correctly
[2025-04-06T20:00:22.311+0000] {logging_mixin.py:151} INFO - [S3]Restaurant Restaurant Japon√®s Kin Sushi Bar uploaded correctly
[2025-04-06T20:00:24.961+0000] {logging_mixin.py:151} INFO - [S3]Restaurant Bar Restaurant Amsterdam uploaded correctly
[2025-04-06T20:00:24.975+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-04-06T20:00:25.053+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=googlemaps_api, task_id=run_API_GM, execution_date=20250406T190000, start_date=20250406T200003, end_date=20250406T200025
[2025-04-06T20:00:25.198+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-04-06T20:00:25.341+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
